GO
/****** Object:  Table [dbo].[Endereco]    Script Date: 20/11/2021 12:41:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Endereco](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LOGRADOURO] [varchar](256) NULL,
	[NUMERO] [int] NOT NULL,
	[CEP] [int] NOT NULL,
	[BAIRRO] [varchar](50) NULL,
	[CIDADE] [varchar](30) NULL,
	[UF] [varchar](20) NULL,
 CONSTRAINT [PK_Endereco] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Pessoa]    Script Date: 20/11/2021 12:41:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Pessoa](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](256) NOT NULL,
	[CPF] [bigint] NOT NULL,
	[ENDERECO] [int] NULL,
 CONSTRAINT [PK_Pessoa] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Pessoa_telefone]    Script Date: 20/11/2021 12:41:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pessoa_telefone](
	[ID_PESSOA] [int] /*IDENTITY(1,1)*/ NOT NULL,
	[ID_TELEFONE] [int] NOT NULL,
 CONSTRAINT [PK_Pessoa_telefone] PRIMARY KEY CLUSTERED 
(
	[ID_PESSOA] ASC,
	[ID_TELEFONE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Telefone]    Script Date: 20/11/2021 12:41:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Telefone](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Numero] [int] NOT NULL,
	[DDD] [int] NOT NULL,
	[Tipo] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Telefone_Tipo]    Script Date: 20/11/2021 12:41:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Telefone_Tipo](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Tipo] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[Endereco] ON 

GO
INSERT [dbo].[Endereco] ([ID], [LOGRADOURO], [NUMERO], [CEP], [BAIRRO], [CIDADE], [UF]) VALUES (2, N'RUA ALCIDES MAIA ', 136, 13474540, N'ZANAGA', N'AMERICANA', N'SP')
GO
INSERT [dbo].[Endereco] ([ID], [LOGRADOURO], [NUMERO], [CEP], [BAIRRO], [CIDADE], [UF]) VALUES (3, N'RUA JOSEFA LOURENCO DOS SANTOS', 137, 55294660, N'MAGANO', N'GATRANHUS', N'PE')
GO
INSERT [dbo].[Endereco] ([ID], [LOGRADOURO], [NUMERO], [CEP], [BAIRRO], [CIDADE], [UF]) VALUES (4, N'RUA PIAUI', 138, 38405244, N'CUSTODIO', N'UBERLANDIA', N'MG')
GO
SET IDENTITY_INSERT [dbo].[Endereco] OFF
GO
SET IDENTITY_INSERT [dbo].[Pessoa] ON 

GO
INSERT [dbo].[Pessoa] ([ID], [NOME], [CPF], [ENDERECO]) VALUES (1, N'CRISTIANE', 40929802802, 2)
GO
INSERT [dbo].[Pessoa] ([ID], [NOME], [CPF], [ENDERECO]) VALUES (2, N'MARIA', 59042542020, 3)
GO
INSERT [dbo].[Pessoa] ([ID], [NOME], [CPF], [ENDERECO]) VALUES (3, N'JOSE', 47562690014, 4)
GO
SET IDENTITY_INSERT [dbo].[Pessoa] OFF

GO
SET IDENTITY_INSERT [dbo].[Pessoa_telefone] ON 

GO
INSERT [dbo].[Pessoa_telefone] ([ID_PESSOA], [ID_TELEFONE]) VALUES (1, 1)
GO
INSERT [dbo].[Pessoa_telefone] ([ID_PESSOA], [ID_TELEFONE]) VALUES (2, 2)
--GO
--SET IDENTITY_INSERT [dbo].[Pessoa_telefone] OFF

GO
SET IDENTITY_INSERT [dbo].[Telefone] ON 

GO
INSERT [dbo].[Telefone] ([ID], [Numero], [DDD], [Tipo]) VALUES (1, 992638694, 19, 1)
GO
INSERT [dbo].[Telefone] ([ID], [Numero], [DDD], [Tipo]) VALUES (2, 23454688, 79, 2)
GO
INSERT [dbo].[Telefone] ([ID], [Numero], [DDD], [Tipo]) VALUES (3, 35527846, 95, 3)
GO
SET IDENTITY_INSERT [dbo].[Telefone] OFF
GO
SET IDENTITY_INSERT [dbo].[Telefone_Tipo] ON 

GO
INSERT [dbo].[Telefone_Tipo] ([ID], [Tipo]) VALUES (1, N'CELULAR')
GO
INSERT [dbo].[Telefone_Tipo] ([ID], [Tipo]) VALUES (2, N'RESIDENCIA')
GO
INSERT [dbo].[Telefone_Tipo] ([ID], [Tipo]) VALUES (3, N'COMERCIAL')
GO
INSERT [dbo].[Telefone_Tipo] ([ID], [Tipo]) VALUES (4, N'RECADO')
GO
SET IDENTITY_INSERT [dbo].[Telefone_Tipo] OFF
GO
ALTER TABLE [dbo].[Pessoa]  WITH CHECK ADD  CONSTRAINT [fk_P] FOREIGN KEY([ENDERECO])
REFERENCES [dbo].[Endereco] ([ID])
GO
ALTER TABLE [dbo].[Pessoa] CHECK CONSTRAINT [fk_P]
GO
ALTER TABLE [dbo].[Pessoa]  WITH CHECK ADD  CONSTRAINT [fk_PesCarro] FOREIGN KEY([ENDERECO])
REFERENCES [dbo].[Endereco] ([ID])
GO
ALTER TABLE [dbo].[Pessoa] CHECK CONSTRAINT [fk_PesCarro]
GO
ALTER TABLE [dbo].[Pessoa_telefone]  WITH CHECK ADD  CONSTRAINT [fk_Pessoa_telefone] FOREIGN KEY([ID_PESSOA], [ID_TELEFONE])
REFERENCES [dbo].[Pessoa_telefone] ([ID_PESSOA], [ID_TELEFONE])
GO
ALTER TABLE [dbo].[Pessoa_telefone] CHECK CONSTRAINT [fk_Pessoa_telefone]
GO
ALTER TABLE [dbo].[Telefone]  WITH CHECK ADD  CONSTRAINT [fk_Pesfone] FOREIGN KEY([Tipo])
REFERENCES [dbo].[Telefone_Tipo] ([ID])
GO
ALTER TABLE [dbo].[Telefone] CHECK CONSTRAINT [fk_Pesfone]
GO
